-- this table store all the information related to the activity of the patient

DROP TABLE IF EXISTS ACTIVITY_INFO; 

CREATE TABLE IF NOT EXISTS ACTIVITY_INFO(
	ACTIVITY_TYPE CHARACTER VARYING(30),
	ACTIVITY_ID BIGINT NOT NULL DEFAULT NEXTVAL('ACTIVITY_ID_SEQ'::regclass), -- STARTS AT 12000
	USER_ID BIGINT NOT NULL,
	TIME_OF_ACTIVITY DATE,
	HOURS_OF_SLEEP INTEGER,
	CALORIES_BURNT INTEGER,
	BLOOD_PRESSURE INTEGER,
	ACTIVITY_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP)


	