-- THIS IS AN AUTO INCREMENT VALUE FOR THE ACTIVITY ID VALUE

DROP SEQUENCE IF EXISTS ACTIVITY_ID_SEQ;

CREATE SEQUENCE ACTIVITY_ID_SEQ
	START 12000
	INCREMENT 1
	NO MAXVALUE
	NO MINVALUE
	NO CYCLE