/*This tables all the information related to the blood data report*/

DROP TABLE IF EXISTS BLOOD_GLUCOSE_INFO;

CREATE TABLE BLOOD_GLUCOSE_INFO(
	HAEMOGLOBIN_COUNT BIGINT,
	PRE_FAST_BLOOD_SUGAR BIGINT,
	POST_FAST_BLOOD_SUGAR BIGINT,
	CHOLESTEROL BIGINT,
	AHDL_CHOLESTEROL BIGINT,
	LDL_CHOLESTEROL BIGINT,
	USER_ID BIGINT NOT NULL, -- refers to the user for whom the test's are being taken
	BLOOD_TEST_ID BIGINT NOT NULL DEFAULT NEXTVAL('blood_test_id_seq'::regclass), -- starts at 9000
	DATE_OF_BLOOD_TEST TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	)
