DROP TABLE IF EXISTS BLOOD_TEST_INFO;

CREATE TABLE BLOOD_TEST_INFO
(
  HAEMOGLOBIN_COUNT BIGINT,
  CHOLESTEROL BIGINT,
  AHDL_CHOLESTEROL BIGINT,
  LDL_CHOLESTEROL BIGINT,
  USER_ID BIGINT NOT NULL,
  BLOOD_TEST_ID BIGINT NOT NULL DEFAULT NEXTVAL('BLOOD_TEST_ID_SEQ'::REGCLASS),
  BLOOD_TEST_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
)