/*The auto increment value for the blood test value*/

DROP SEQUENCE IF EXISTS BLOOD_TEST_ID_SEQ;
CREATE SEQUENCE BLOOD_TEST_ID_SEQ
	START 9000
	INCREMENT 1
	NO MAXVALUE
	NO MINVALUE
	NO CYCLE;