/*This table will store all the information related the doctor */

DROP TABLE IF EXISTS DOCTOR_INFO;

CREATE TABLE IF NOT EXISTS DOCTOR_INFO(
	FIRST_NAME CHARACTER VARYING(30) NOT NULL,
	LAST_NAME CHARACTER VARYING(30) NOT NULL,
	QUALIFICATION CHARACTER VARYING(100) NOT NULL,
	PHONE_NUMBER CHARACTER VARYING(20) NOT NULL,
	EMAIL CHARACTER VARYING(30) NOT NULL,
	CITY CHARACTER VARYING(30) NOT NULL,
	ZIPCODE CHARACTER VARYING(30) NOT NULL,
	COUNTRY CHARACTER VARYING(30) NOT NULL,
	DOCTOR_ID BIGINT NOT NULL DEFAULT NEXTVAL('doctor_id_seq'::regclass); -- STARTS AT 12345
	)

	
	
