/*
This table will store the static data related to the user
*/

DROP TABLE IF EXISTS USER_INFO;

CREATE TABLE IF NOT EXISTS USER_INFO(
	FIRST_NAME CHARACTER VARYING(30) NOT NULL,
	LAST_NAME CHARACTER VARYING(30) NOT NULL,
	SEX CHARACTER VARYING(2) NOT NULL, /* Assuming the I/P are M or F */
	WEIGHT NUMERIC(3,2) NOT NULL,
	HEIGHT NUMERIC(3,2) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	DIABETES_TYPE CHARACTER VARYING(10) NOT NULL,
	ADDRESS CHARACTER VARYING(100),
	CITY CHARACTER VARYING(20),
	ZIPCODE CHARACTER VARYING(20),
	COUNTRY CHARACTER VARYING(30),
	EMAIL CHARACTER VARYING(50) NOT NULL,
	PHONE_NUMBER CHARACTER VARYING(20) NOT NULL,
	USER_ID BIGINT NOT NULL DEFAULT nextval('user_id_seq'::regclass), -- STARTS AT 1
	USER_SIGN_UP_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DOCTOR_ID BIGINT,
	PASSWORD CHARACTER VARYING(256) NOT NULL
	)



	
